name: Run Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.19", "1.20", "1.21"]

    runs-on: ubuntu-latest

    name: Go ${{ matrix.go }} Tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: make test

      - name: Run Coverage
        run: go test -v -cover ./...
